[workspace]
members = [ 
    "ctor", 
    "dtor", 
    "ctor-proc-macro",
    "dtor-proc-macro",
    "shared",
    "tests/system", 
    "tests/wasm", 
    "tests/edition-2018", 
    "tests/edition-2021", 
    "tests/edition-2024" 
]
default-members = [
    "ctor",
    "dtor",
    "ctor-proc-macro",
    "dtor-proc-macro",
    "shared",
    "tests/system",
    "tests/wasm",
    "tests/edition-2018",
    "tests/edition-2021",
]
resolver = "2"
dependencies = { wasm-bindgen = {version = "=0.2.100"} }

[patch.crates-io]
ctor = { path = "ctor" }
dtor = { path = "dtor" }
dtor-proc-macro = { path = "dtor-proc-macro" }
ctor-proc-macro = { path = "ctor-proc-macro" }
