[package]
name = "ctor"
version = "0.3.2"
authors = ["Matt Mastracci <matthew@mastracci.com>"]
edition = "2021"
description = "__attribute__((constructor)) for Rust"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/mmastrac/rust-ctor"
readme = "../README.md"

[badges]
travis-ci = { repository = "mmastrac/rust-ctor", branch = "master" }

[features]
default = []

# For nightly users, used(linker) may be a better choice
used_linker = ["ctor-proc-macro/used_linker"]
# This will eventually become the default
__warn_on_missing_unsafe = ["ctor-proc-macro/__warn_on_missing_unsafe"]

[dependencies]
ctor-proc-macro = "=0.0.2"

[dev-dependencies]
libc-print = "0.1.20"

[[example]]
name = "example"
path = "src/example.rs"
