[package]
name = "shared"
version = "0.1.0"
edition = "2018"
publish = false

[features]
used_linker = []
__no_warn_on_missing_unsafe = []

[dependencies]
macrotest = "1"
trybuild = "1"

# Prevents warning about unused patch version
ctor = "*"
